# Generated by Django 5.1.4 on 2024-12-21 10:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_award_decision_sociallink_alter_partner_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCountryAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
