# Generated by Django 5.1.4 on 2024-12-21 10:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutcountryaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='biography',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
    ]
