# Generated by Django 5.1.4 on 2024-12-22 10:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_award_description_alter_partner_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='description_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
