# Generated by Django 5.1.4 on 2024-12-22 10:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aboutcountryaward_text_de_aboutcountryaward_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_cv',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_es',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_fr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_kk',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_uz_latn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutcountryaward',
            name='Text_zh',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_cv',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_kk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_uz_latn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='description_zh',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_cv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_uz_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='award',
            name='name_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_cv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_uz_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='decision',
            name='name_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_cv',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_kk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_uz_latn',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_zh',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_cv',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_uz_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_cv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_uz_latn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_zh',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_cv',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_uz_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='name_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
