# Generated by Django 5.1.4 on 2024-12-23 21:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_aboutcountryaward_text_en_aboutcountryaward_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='biography_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='biography_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='partner',
            name='position_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
    ]
